#!/usr/bin/env node

/**
 * Build script for frontend
 * Injects environment variables into config.js
 * Run this before deploying to Vercel
 */

const fs = require('fs');
const path = require('path');

// Get API URL from environment variable or use default
const API_BASE = process.env.VERCEL_ENV 
  ? process.env.NEXT_PUBLIC_API_URL || process.env.API_URL || 'https://your-backend-name.onrender.com'
  : (process.env.API_URL || 'http://localhost:3000');

// Generate config.js content
const configContent = `// API Configuration
// This file is auto-generated by build.js
// DO NOT EDIT MANUALLY - it will be overwritten
window.API_CONFIG = {
  API_BASE: "${API_BASE}"
};
`;

// Write config.js
const configPath = path.join(__dirname, 'config.js');
fs.writeFileSync(configPath, configContent, 'utf-8');

console.log('✅ Generated config.js with API_BASE:', API_BASE);

